spring:
  config:
    activate:
      on-profile: local
    import: optional:file:./inhagit-server-secret/application-local.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:./inhagit-server-secret/application-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:./inhagit-server-secret/application-prod.yml
---